#comment out everything
from django.urls import *
from django.conf.urls import url
from costtool import views as myviews
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Examples:
    url(r'^index.html$', myviews.index, name='index'), 
    url(r'^logout.html$', myviews.logout, name='logout'),
    url(r'^$', myviews.about, name='about'),
    url(r'^manual.html$', myviews.manual, name='manual'),
    url(r'^CostOut Manual 2015.docx$', myviews.manual1, name='manual1'),
    url(r'^CostOut Screenshots.docx$', myviews.manual2, name='manual2'),
    url(r'^DBofPrices.xlsx$', myviews.xl1, name='xl1'),
    url(r'^InflationIndex.xlsx$', myviews.xl2, name='xl2'),
    url(r'^GeographicalIndex.xlsx$', myviews.xl3, name='xl3'),
    url(r'^Internal_Updating the CostOut Database Handbook.docx$', myviews.doc1, name='doc1'),
    url(r'^Tutorial template.docx$', myviews.doc2, name='doc2'),
    url(r'^Developer Instructions.docx$', myviews.doc3, name='doc3'),

    url(r'^admin/options.html$', myviews.options, name='options'),
    url(r'^admin/userreports.html$', myviews.userreports, name='userreports'),
    url(r'^admin/myaccount.html$', myviews.myaccount, name='myaccount'),
    url(r'^admin/contact.html$', myviews.contact, name='contact'),
    url(r'^admin/upload.html$', myviews.upload, name='upload'),
    url(r'^admin/tech.html$', myviews.tech, name='tech'),
    url(r'^admin/Internal_Updating the CostOut Database Handbook.docx$', myviews.tech1, name='tech1'),
    url(r'^admin/Developer Instructions.docx$', myviews.tech2, name='tech2'),
    url(r'^admin/videos.html$', myviews.videos, name='videos'),
    
    url(r'^reports/proj_table.html$', myviews.proj_table, name='proj_table'),
    url(r'^reports/users_table.html$', myviews.users_table, name='users_table'),
    url(r'^reports/export_proj.html$', myviews.export_proj, name='export_proj'),
    url(r'^reports/export_users.html$', myviews.export_users, name='export_users'),
    url(r'^reports/(?P<user_id>\d+)/del_user.html$',myviews.del_user, name='del_user'),
    url(r'^reports/noofreg.html$', myviews.noofreg, name='noofreg'),
    url(r'^reports/cumulreg.html$', myviews.cumulreg, name='cumulreg'),
    
    url(r'^Quickstart.docx$', myviews.quickstart, name='quickstart'),
    url(r'^tour$', myviews.tour, name='tour'),
    url(r'^tutorial1$', myviews.tutorial1, name='tutorial1'),
    url(r'^tutorial2$', myviews.tutorial2, name='tutorial2'),
    url(r'^tutorial3$', myviews.tutorial3, name='tutorial3'),
    url(r'^tutorial4$', myviews.tutorial4, name='tutorial4'),
    url(r'^tutorial5$', myviews.tutorial5, name='tutorial5'),
    url(r'^license2.html$', myviews.license2, name='license2'),
    url(r'^additional.html$', myviews.additional, name='additional'), 
    url(r'^Online Private Institution Tool Kit License.pdf$', myviews.private_pdf, name='private_pdf'),
    url(r'^Online Public Institution Tool Kit License.pdf$', myviews.public_pdf, name='public_pdf'),
    url(r'^Average Size of Educational Facilities.xlsx$', myviews.add1, name='add1'),
    url(r'^Calculating Cost Differences Between Programs.pdf$', myviews.add2, name='add2'),
    url(r'^CostOut Feedback Form.docx$', myviews.add3, name='add3'),
    url(r'^Database of Benefits Rates.xls$', myviews.add4, name='add4'),
    url(r'^Example Interview Protocol.pdf$', myviews.add5, name='add5'),
    url(r'^Formulas used in CostOut.pdf$', myviews.add6, name='add6'),
    url(r'^Sources of Prices and Benefits.pdf$', myviews.add7, name='add7'),
    url(r'^Finding National Prices.pdf$', myviews.add8, name='add8'),

    url(r'^tutorials.html$', myviews.tutorials, name='tutorials'),
    url(r'^Tutorial 1 Add personnel ingredient.pdf$', myviews.tutorial1_pdf, name='tutorial1_pdf'),  
    url(r'^Tutorial 2 Adding a new ingredient.pdf$', myviews.tutorial2_pdf, name='tutorial2_pdf'),
    url(r'^Tutorial 3 How to choose a price.pdf$', myviews.tutorial3_pdf, name='tutorial3_pdf'),
    url(r'^Tutorial 4 Project Settings.pdf$', myviews.tutorial4_pdf, name='tutorial4_pdf'), 
    url(r'^Tutorial 5 Adding facilities prices.pdf$', myviews.tutorial5_pdf, name='tutorial5_pdf'), 

    url(r'^register/Online-Cost-Tool-Kit-License_Public_Institutions.pdf$', myviews.return_pdf, name='return_pdf'),

    url(r'^prices/add_price.html$', myviews.add_price, name='add_price'),
    url(r'^prices/price_list.html$', myviews.price_list, name='price_list'),
    url(r'^prices/my_price_list.html$', myviews.my_price_list, name='my_price_list'),
    url(r'^prices/prices.html$', myviews.prices, name='prices'),

    url(r'^reports/(?P<project_id>\d+)/reports.html$', myviews.reports, name='reports'),
    url(r'^reports/costanal.html$', myviews.costanal, name='costanal'),
    url(r'^reports/costanalbyyear.html$', myviews.costanalbyyear, name='costanalbyyear'),
    url(r'^reports/costeff.html$', myviews.costeff, name='costeff'),
    url(r'^reports/costeff_table.html$', myviews.costeff_table, name='costeff_table'),
    url(r'^reports/export_cea.html$', myviews.export_cea, name='export_cea'),
    url(r'^reports/export_ca.html$', myviews.export_ca, name='export_ca'),
    url(r'^reports/compcostanal.html$', myviews.compcostanal, name='compcostanal'),
    url(r'^reports/ca_table.html$', myviews.ca_table, name='ca_table'),

    url(r'^prices/imports.html$', myviews.imports, name='imports'),
    url(r'^prices/clear_prices.html$', myviews.clear_prices, name='clear_prices'),
    url(r'^prices/(?P<price_id>\d+)/view_price.html$', myviews.view_price, name='view_price'),
    url(r'^prices/(?P<price_id>\d+)/edit_price.html$', myviews.edit_price, name='edit_price'),
    url(r'^prices/(?P<price_id>\d+)/del_price.html$', myviews.del_price, name='del_price'),
    url(r'^prices/import_excel.html$', myviews.import_excel, name='import_excel'),
    url(r'^prices/import_geo.html$', myviews.import_geo, name='import_geo'),
    url(r'^prices/import_inf.html$', myviews.import_inf, name='import_inf'),
    url(r'^prices/import_benefits.html$', myviews.import_benefits, name='import_benefits'),
    url(r'^prices/(?P<price_id>\d+)/view_price2.html$', myviews.view_price2, name='view_price2'),
    url(r'^prices/export_prices.html$', myviews.export_prices,  name='export_prices'),
    url(r'^prices/export_cbcse_prices.html$', myviews.export_cbcse_prices,  name='export_cbcse_prices'),

    url(r'^project/add_project.html$', myviews.add_project, name='add_project'),
    url(r'^project/project_list.html$', myviews.project_list, name='project_list'),
    url(r'^project/(?P<project_id>\d+)/del_project.html$', myviews.del_project, name='del_project'),
    url(r'^project/(?P<project_id>\d+)/edit_project.html$', myviews.edit_project, name='edit_project'),
    url(r'^project/(?P<project_id>\d+)/share_project.html$', myviews.share_project, name='share_project'),
    url(r'^project/del_sharproj.html$', myviews.del_sharproj, name='del_sharproj'),     

    url(r'^project/settings.html$', myviews.settings, name='settings'),
    url(r'^project/(?P<project_id>\d+)/add_settings.html$', myviews.add_settings, name='add_settings'),
    url(r'^project/indices.html$', myviews.indices, name='indices'),
    url(r'^project/geo.html$', myviews.addedit_geo, name='addedit_geo'),
    url(r'^project/restore_geo.html$', myviews.restore_geo, name='restore_geo'),
    url(r'^project/inflation.html$', myviews.addedit_inf, name='addedit_inf'),
    url(r'^project/restore_inf.html$', myviews.restore_inf, name='restore_inf'),
    url(r'^project/export_to_inf.html$', myviews.export_to_inf, name='export_to_inf'),
    url(r'^project/export_to_geo.html$', myviews.export_to_geo, name='export_to_geo'),
    url(r'^project/(?P<project_id>\d+)/dupl_project.html$',myviews.dupl_project, name='dupl_project'),

    url(r'^project/programs/(?P<project_id>\d+)/program_list.html$',myviews.program_list, name='program_list'),
    url(r'^project/programs/add_program.html$', myviews.add_program, name='add_program'),
    url(r'^project/programs/(?P<program_id>\d+)/del_program.html$',myviews.del_program, name='del_program'),
    url(r'^project/programs/(?P<program_id>\d+)/dupl_program.html$',myviews.dupl_program, name='dupl_program'),
    url(r'^project/programs/(?P<program_id>\d+)/edit_program.html$',myviews.edit_program, name='edit_program'),

    url(r'^project/programs/effect/(?P<project_id>\d+)/(?P<program_id>\d+)/tabbedview.html$', myviews.tabbedlayout, name='tabbedlayout'),
    url(r'^project/programs/export_progdesc.html$', myviews.export_progdesc,  name='export_progdesc'),

    url(r'^project/programs/costs/search_costs.html$', myviews.search_costs, name='search_costs'),
    url(r'^project/programs/costs/price_search_results.html$', myviews.price_search, name='price_search'),
    url(r'^project/programs/costs/(?P<price_id>\d+)/price_indices.html$', myviews.price_indices, name='price_indices'),
    url(r'^project/programs/costs/(?P<price_id>\d+)/nonper_indices.html$', myviews.nonper_indices, name='nonper_indices'),
    url(r'^project/programs/costs/(?P<price_id>\d+)/decideCat.html$', myviews.decideCat, name='decideCat'),
    url(r'^project/programs/costs/(?P<price_id>\d+)/price_benefits.html$', myviews.price_benefits, name='price_benefits'),
    url(r'^project/programs/costs/benefits.html$', myviews.benefits, name='benefits'),
    url(r'^project/programs/costs/(?P<ben_id>\d+)/save_benefit.html$', myviews.save_benefit, name='save_benefit'),
    url(r'^project/programs/costs/gotoinf.html$', myviews.gotoinf, name='gotoinf'),

    url(r'^project/programs/costs/wage_converter.html$', myviews.wage_converter, name='wage_converter'),
    url(r'^project/programs/costs/wage_defaults.html$', myviews.wage_defaults, name='wage_defaults'),
    url(r'^project/programs/costs/summary.html$', myviews.price_summary, name='price_summary'),
    url(r'^project/programs/costs/full_table.html$', myviews.full_table,  name='full_table'),
    url(r'^project/programs/costs/export_cost_table.html$', myviews.export_cost_table,  name='export_cost_table'),
    url(r'^project/programs/costs/export_full_table.html$', myviews.export_full_table,  name='export_full_table'),

    url(r'^project/programs/costs/umconverter.html$', myviews.um_converter, name='um_converter'),
    url(r'^project/programs/costs/(?P<ing_id>\d+)/del_ingredient.html$', myviews.del_ingredient, name='del_ingredient'),
    url(r'^project/programs/costs/(?P<ing_id>\d+)/dupl_ingredient.html$', myviews.dupl_ingredient, name='dupl_ingredient'),

    url(r'^project/programs/dist/add_agency.html$', myviews.add_agency, name='add_agency'),
    url(r'^project/programs/dist/export_dist.html$', myviews.export_dist,  name='export_dist'),

    url(r'^project/programs/transfer/add_transfer.html$', myviews.add_transfer, name='add_transfer'),
    url(r'^project/programs/transfer/(?P<trans_id>\d+)/del_transfer.html$', myviews.del_transfer, name='del_transfer'),
    #url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    #url(r'^admin/', include(admin.site.urls)),
    url(r'^register/register.html$', myviews.register, name='register'),
    url(r'^register/license.html$', myviews.license, name='license'),
    url(r'^login/login.html$', myviews.login, name='login'),
    url(r'^login/forgot.html$', myviews.forgot, name='forgot'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

