from django.conf.urls import include, url
from django.contrib import admin
#from costtool import views
from costtool import views as costtool_views

from django.conf import settings
from django.conf.urls.static import static
admin.autodiscover()

urlpatterns = [
    # Examples:
    url(r'^index.html$', costtool_views.index, name='index'),
    url(r'^about.html$', costtool_views.about, name='about'),
    url(r'^logout.html$', costtool_views.logout, name='logout'),
    url(r'^$', costtool_views.about, name='about'),
    url(r'^manual.html$', costtool_views.manual, name='manual'),
    url(r'^CostOut Manual 2015.docx$', costtool_views.manual1, name='manual1'),
    url(r'^CostOut Screenshots.docx$', costtool_views.manual2, name='manual2'),
    url(r'^DBofPrices.xlsx$', costtool_views.xl1, name='xl1'),
    url(r'^InflationIndex.xlsx$', costtool_views.xl2, name='xl2'),
    url(r'^GeographicalIndex.xlsx$', costtool_views.xl3, name='xl3'),
    url(r'^Internal_Updating the CostOut Database Handbook.docx$', costtool_views.doc1, name='doc1'),
    url(r'^Tutorial template.docx$', costtool_views.doc2, name='doc2'),
    url(r'^Developer Instructions.docx$', costtool_views.doc3, name='doc3'),

    url(r'^admin/options.html$', costtool_views.options, name='options'),
    url(r'^admin/userreports.html$', costtool_views.userreports, name='userreports'),
    url(r'^admin/myaccount.html$', costtool_views.myaccount, name='myaccount'),
    url(r'^admin/contact.html$', costtool_views.contact, name='contact'),
    url(r'^admin/upload.html$', costtool_views.upload, name='upload'),
    url(r'^admin/tech.html$', costtool_views.tech, name='tech'),
    #url(r'^admin/Internal_Updating the CostOut Database Handbook.docx$', costtool_views.tech1, name='tech1'),
    url(r'^admin/Developer Instructions.docx$', costtool_views.tech2, name='tech2'),
    url(r'^admin/videos.html$', costtool_views.videos, name='videos'),
    
    url(r'^reports/proj_table.html$', costtool_views.proj_table, name='proj_table'),
    url(r'^reports/users_table.html$', costtool_views.users_table, name='users_table'),
    url(r'^reports/export_proj.html$', costtool_views.export_proj, name='export_proj'),
    url(r'^reports/export_users.html$', costtool_views.export_users, name='export_users'),
    url(r'^reports/(?P<user_id>\d+)/del_user.html$',costtool_views.del_user, name='del_user'),
    url(r'^reports/noofreg.html$', costtool_views.noofreg, name='noofreg'),
    url(r'^reports/cumulreg.html$', costtool_views.cumulreg, name='cumulreg'),
    
    url(r'^Quickstart.docx$', costtool_views.quickstart, name='quickstart'),
    url(r'^tour$', costtool_views.tour, name='tour'),
    url(r'^tutorial1$', costtool_views.tutorial1, name='tutorial1'),
    url(r'^tutorial2$', costtool_views.tutorial2, name='tutorial2'),
    url(r'^tutorial3$', costtool_views.tutorial3, name='tutorial3'),
    url(r'^tutorial4$', costtool_views.tutorial4, name='tutorial4'),
    url(r'^tutorial5$', costtool_views.tutorial5, name='tutorial5'),
    url(r'^license2.html$', costtool_views.license2, name='license2'),
    url(r'^additional.html$', costtool_views.additional, name='additional'), 
    url(r'^Online Private Institution Tool Kit License.pdf$', costtool_views.private_pdf, name='private_pdf'),
    url(r'^Online Public Institution Tool Kit License.pdf$', costtool_views.public_pdf, name='public_pdf'),
    url(r'^Average Size of Educational Facilities.xlsx$', costtool_views.add1, name='add1'),
    url(r'^Calculating Cost Differences Between Programs.pdf$', costtool_views.add2, name='add2'),
    url(r'^CostOut Feedback Form.docx$', costtool_views.add3, name='add3'),
    url(r'^Database of Benefits Rates.xls$', costtool_views.add4, name='add4'),
    url(r'^Example Interview Protocol.pdf$', costtool_views.add5, name='add5'),
    url(r'^Formulas used in CostOut.pdf$', costtool_views.add6, name='add6'),
    url(r'^Sources of Prices and Benefits.pdf$', costtool_views.add7, name='add7'),
    url(r'^Finding National Prices.pdf$', costtool_views.add8, name='add8'),

    url(r'^tutorials.html$', costtool_views.tutorials, name='tutorials'),
    url(r'^Tutorial 1 Add personnel ingredient.pdf$', costtool_views.tutorial1_pdf, name='tutorial1_pdf'),  
    url(r'^Tutorial 2 Adding a new ingredient.pdf$', costtool_views.tutorial2_pdf, name='tutorial2_pdf'),
    url(r'^Tutorial 3 How to choose a price.pdf$', costtool_views.tutorial3_pdf, name='tutorial3_pdf'),
    url(r'^Tutorial 4 Project Settings.pdf$', costtool_views.tutorial4_pdf, name='tutorial4_pdf'), 
    url(r'^Tutorial 5 Adding facilities prices.pdf$', costtool_views.tutorial5_pdf, name='tutorial5_pdf'), 

    url(r'^register/Online-Cost-Tool-Kit-License_Public_Institutions.pdf$', costtool_views.return_pdf, name='return_pdf'),

    url(r'^prices/add_price.html$', costtool_views.add_price, name='add_price'),
    url(r'^prices/price_list.html$', costtool_views.price_list, name='price_list'),
    url(r'^prices/my_price_list.html$', costtool_views.my_price_list, name='my_price_list'),
    url(r'^prices/prices.html$', costtool_views.prices, name='prices'),

    url(r'^reports/(?P<project_id>\d+)/reports.html$', costtool_views.reports, name='reports'),
    url(r'^reports/costanal.html$', costtool_views.costanal, name='costanal'),
    url(r'^reports/costanalbyyear.html$', costtool_views.costanalbyyear, name='costanalbyyear'),
    url(r'^reports/costeff.html$', costtool_views.costeff, name='costeff'),
    url(r'^reports/costeff_table.html$', costtool_views.costeff_table, name='costeff_table'),
    url(r'^reports/export_cea.html$', costtool_views.export_cea, name='export_cea'),
    url(r'^reports/export_ca.html$', costtool_views.export_ca, name='export_ca'),
    url(r'^reports/compcostanal.html$', costtool_views.compcostanal, name='compcostanal'),
    url(r'^reports/ca_table.html$', costtool_views.ca_table, name='ca_table'),

    url(r'^prices/imports.html$', costtool_views.imports, name='imports'),
    url(r'^prices/clear_prices.html$', costtool_views.clear_prices, name='clear_prices'),
    url(r'^prices/(?P<price_id>\d+)/view_price.html$', costtool_views.view_price, name='view_price'),
    url(r'^prices/(?P<price_id>\d+)/edit_price.html$', costtool_views.edit_price, name='edit_price'),
    url(r'^prices/(?P<price_id>\d+)/del_price.html$', costtool_views.del_price, name='del_price'),
    url(r'^prices/import_excel.html$', costtool_views.import_excel, name='import_excel'),
    url(r'^prices/import_geo.html$', costtool_views.import_geo, name='import_geo'),
    url(r'^prices/import_inf.html$', costtool_views.import_inf, name='import_inf'),
    url(r'^prices/import_benefits.html$', costtool_views.import_benefits, name='import_benefits'),
    url(r'^prices/(?P<price_id>\d+)/view_price2.html$', costtool_views.view_price2, name='view_price2'),
    url(r'^prices/export_prices.html$', costtool_views.export_prices,  name='export_prices'),
    url(r'^prices/export_cbcse_prices.html$', costtool_views.export_cbcse_prices,  name='export_cbcse_prices'),

    url(r'^project/add_project.html$', costtool_views.add_project, name='add_project'),
    url(r'^project/project_list.html$', costtool_views.project_list, name='project_list'),
    url(r'^project/(?P<project_id>\d+)/del_project.html$', costtool_views.del_project, name='del_project'),
    url(r'^project/(?P<project_id>\d+)/edit_project.html$', costtool_views.edit_project, name='edit_project'),
    url(r'^project/(?P<project_id>\d+)/share_project.html$', costtool_views.share_project, name='share_project'),
    url(r'^project/del_sharproj.html$', costtool_views.del_sharproj, name='del_sharproj'),     

    url(r'^project/settings.html$', costtool_views.settings, name='settings'),
    url(r'^project/(?P<project_id>\d+)/add_settings.html$', costtool_views.add_settings, name='add_settings'),
    url(r'^project/indices.html$', costtool_views.indices, name='indices'),
    url(r'^project/geo.html$', costtool_views.addedit_geo, name='addedit_geo'),
    url(r'^project/restore_geo.html$', costtool_views.restore_geo, name='restore_geo'),
    url(r'^project/inflation.html$', costtool_views.addedit_inf, name='addedit_inf'),
    url(r'^project/restore_inf.html$', costtool_views.restore_inf, name='restore_inf'),
    url(r'^project/export_to_inf.html$', costtool_views.export_to_inf, name='export_to_inf'),
    url(r'^project/export_to_geo.html$', costtool_views.export_to_geo, name='export_to_geo'),
    url(r'^project/(?P<project_id>\d+)/dupl_project.html$',costtool_views.dupl_project, name='dupl_project'),

    url(r'^project/programs/(?P<project_id>\d+)/program_list.html$',costtool_views.program_list, name='program_list'),
    url(r'^project/programs/add_program.html$', costtool_views.add_program, name='add_program'),
    url(r'^project/programs/(?P<program_id>\d+)/del_program.html$',costtool_views.del_program, name='del_program'),
    url(r'^project/programs/(?P<program_id>\d+)/dupl_program.html$',costtool_views.dupl_program, name='dupl_program'),
    url(r'^project/programs/(?P<program_id>\d+)/edit_program.html$',costtool_views.edit_program, name='edit_program'),

    url(r'^project/programs/effect/(?P<project_id>\d+)/(?P<program_id>\d+)/tabbedview.html$', costtool_views.tabbedlayout, name='tabbedlayout'),
    url(r'^project/programs/export_progdesc.html$', costtool_views.export_progdesc,  name='export_progdesc'),

    url(r'^project/programs/costs/search_costs.html$', costtool_views.search_costs, name='search_costs'),
    url(r'^project/programs/costs/price_search_results.html$', costtool_views.price_search, name='price_search'),
    url(r'^project/programs/costs/(?P<price_id>\d+)/price_indices.html$', costtool_views.price_indices, name='price_indices'),
    url(r'^project/programs/costs/(?P<price_id>\d+)/nonper_indices.html$', costtool_views.nonper_indices, name='nonper_indices'),
    url(r'^project/programs/costs/(?P<price_id>\d+)/decideCat.html$', costtool_views.decideCat, name='decideCat'),
    url(r'^project/programs/costs/(?P<price_id>\d+)/price_benefits.html$', costtool_views.price_benefits, name='price_benefits'),
    url(r'^project/programs/costs/benefits.html$', costtool_views.benefits, name='benefits'),
    url(r'^project/programs/costs/(?P<ben_id>\d+)/save_benefit.html$', costtool_views.save_benefit, name='save_benefit'),
    url(r'^project/programs/costs/gotoinf.html$', costtool_views.gotoinf, name='gotoinf'),

    url(r'^project/programs/costs/wage_converter.html$', costtool_views.wage_converter, name='wage_converter'),
    url(r'^project/programs/costs/wage_defaults.html$', costtool_views.wage_defaults, name='wage_defaults'),
    url(r'^project/programs/costs/summary.html$', costtool_views.price_summary, name='price_summary'),
    url(r'^project/programs/costs/full_table.html$', costtool_views.full_table,  name='full_table'),
    url(r'^project/programs/costs/export_cost_table.html$', costtool_views.export_cost_table,  name='export_cost_table'),
    url(r'^project/programs/costs/export_full_table.html$', costtool_views.export_full_table,  name='export_full_table'),

    url(r'^project/programs/costs/umconverter.html$', costtool_views.um_converter, name='um_converter'),
    url(r'^project/programs/costs/(?P<ing_id>\d+)/del_ingredient.html$', costtool_views.del_ingredient, name='del_ingredient'),
    url(r'^project/programs/costs/(?P<ing_id>\d+)/dupl_ingredient.html$', costtool_views.dupl_ingredient, name='dupl_ingredient'),

    url(r'^project/programs/dist/add_agency.html$', costtool_views.add_agency, name='add_agency'),
    url(r'^project/programs/dist/export_dist.html$', costtool_views.export_dist,  name='export_dist'),

    url(r'^project/programs/transfer/add_transfer.html$', costtool_views.add_transfer, name='add_transfer'),
    url(r'^project/programs/transfer/(?P<trans_id>\d+)/del_transfer.html$', costtool_views.del_transfer, name='del_transfer'),
    #url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    #url(r'^admin/', include(admin.site.urls)),
    url(r'^register/register.html$', costtool_views.register, name='register'),
    url(r'^register/license.html$', costtool_views.license, name='license'),
    url(r'^login/login.html$', costtool_views.login, name='login'),
    url(r'^login/forgot.html$', costtool_views.forgot, name='forgot'),

    url(r'^index.html$', costtool_views.index, name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

